Unit Model.Lead.PhoneAssignment;

Interface

Uses
    MVCFramework.ActiveRecord,
    MVCFramework.Nullables,
    MVCFramework.Serializer.Commons,
    System.Generics.Collections;

Type
    [MVCNameCase(ncLowerCase)]
    [MVCTable('vw_phone_assignment')]
    [MVCEntityActions([eaRetrieve])]
    TPhoneAssignment = Class(TMVCActiveRecord)
    Private
        [MVCTableField('AssignmentID', [foPrimaryKey, foAutoGenerated])]
        FAssignmentID: Int64;

        [MVCTableField('Phone')]
        FPhone: String;

        [MVCTableField('BranchName')]
        FBranchName: String;

        [MVCTableField('BranchID')]
        FBranchID: Integer;

        [MVCTableField('SourceCollectingDataID')]
        FSourceCollectingDataID: Integer;

        [MVCTableField('SourceName')]
        FSourceName: String;

        [MVCTableField('UserName')]
        FUserName: String;

        [MVCTableField('AddedAt')]
        FAddedAt: TDateTime;

        [MVCTableField('gravity_entry_id')]
        FGravityEntryId: NullableInt64;

        [MVCTableField('gravity_full_name')]
        FGravityFullName: NullableString;

        [MVCTableField('gravity_national_code')]
        FGravityNationalCode: NullableString;

        [MVCTableField('gravity_car_requested')]
        FGravityCarRequested: NullableString;

        [MVCTableField('gravity_sale_terms')]
        FGravitySaleTerms: NullableString;

        [MVCTableField('gravity_address')]
        FGravityAddress: NullableString;

        [MVCTableField('gravity_city')]
        FGravityCity: NullableString;

        [MVCTableField('gravity_color')]
        FGravityColor: NullableString;

        [MVCTableField('gravity_source_url')]
        FGravitySourceUrl: NullableString;

        [MVCTableField('gravity_ip')]
        FGravityIp: NullableString;

        [MVCTableField('gravity_date_created')]
        FGravityDateCreated: NullableTDateTime;

        [MVCTableField('goftino_id')]
        FGoftinoId: NullableInt64;

        [MVCTableField('goftino_name')]
        FGoftinoName: NullableString;

        [MVCTableField('goftino_car_requested')]
        FGoftinoCarRequested: NullableString;

        [MVCTableField('goftino_email')]
        FGoftinoEmail: NullableString;

        [MVCTableField('goftino_description')]
        FGoftinoDescription: NullableString;
    Public
        Property AssignmentID: Int64 Read FAssignmentID Write FAssignmentID;
        Property Phone: String Read FPhone Write FPhone;
        Property BranchID: Integer Read FBranchID Write FBranchID;
        Property BranchName: String Read FBranchName Write FBranchName;
        Property SourceCollectingDataID: Integer Read FSourceCollectingDataID Write FSourceCollectingDataID;
        Property SourceName: String Read FSourceName Write FSourceName;
        Property UserName: String Read FUserName Write FUserName;
        Property AddedAt: TDateTime Read FAddedAt Write FAddedAt;
        Property GravityEntryId: NullableInt64 Read FGravityEntryId Write FGravityEntryId;
        Property GravityFullName: NullableString Read FGravityFullName Write FGravityFullName;
        Property GravityNationalCode: NullableString Read FGravityNationalCode Write FGravityNationalCode;
        Property GravityCarRequested: NullableString Read FGravityCarRequested Write FGravityCarRequested;
        Property GravitySaleTerms: NullableString Read FGravitySaleTerms Write FGravitySaleTerms;
        Property GravityAddress: NullableString Read FGravityAddress Write FGravityAddress;
        Property GravityCity: NullableString Read FGravityCity Write FGravityCity;
        Property GravityColor: NullableString Read FGravityColor Write FGravityColor;
        Property GravitySourceUrl: NullableString Read FGravitySourceUrl Write FGravitySourceUrl;
        Property GravityIp: NullableString Read FGravityIp Write FGravityIp;
        Property GravityDateCreated: NullableTDateTime Read FGravityDateCreated Write FGravityDateCreated;
        Property GoftinoId: NullableInt64 Read FGoftinoId Write FGoftinoId;
        Property GoftinoName: NullableString Read FGoftinoName Write FGoftinoName;
        Property GoftinoCarRequested: NullableString Read FGoftinoCarRequested Write FGoftinoCarRequested;
        Property GoftinoEmail: NullableString Read FGoftinoEmail Write FGoftinoEmail;
        Property GoftinoDescription: NullableString Read FGoftinoDescription Write FGoftinoDescription;
    End;


Implementation

End.
